var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__44d96013._.js")
R.c("server/chunks/ssr/83a34_next_dist_28fcde19._.js")
R.c("server/chunks/ssr/OneDrive_Attachments_Desktop_diary final no editz_bc162d78._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2f3730cd._.js")
R.c("server/chunks/ssr/[root-of-the-server]__cdfbdcd6._.js")
R.c("server/chunks/ssr/83a34_next_dist_8cfd15e0._.js")
R.c("server/chunks/ssr/83a34_next_dist_client_components_builtin_global-error_8e38cb7f.js")
R.c("server/chunks/ssr/[root-of-the-server]__36389b2e._.js")
R.c("server/chunks/ssr/83a34_next_dist_client_components_3a622b27._.js")
R.c("server/chunks/ssr/83a34_next_dist_client_components_builtin_forbidden_83546d85.js")
R.c("server/chunks/ssr/83a34_next_dist_client_components_builtin_unauthorized_2cae79f3.js")
R.c("server/chunks/ssr/dc270_Desktop_diary final no editz__next-internal_server_app_page_actions_31053417.js")
R.m(22863)
module.exports=R.m(22863).exports
